on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: ilyaaid/watch_up
    steps:
      - uses: actions/checkout@v3
      - run: make check

  build:
    runs-on: ubuntu-latest
    container: ilyaaid/watch_up
    needs: [check]
    steps:
      - uses: actions/checkout@v3
      - run: make build

  test:
    runs-on: ubuntu-latest
    container: ilyaaid/watch_up
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - run: make test